apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: fullstacktodo
  creationTimestamp: null
data:
  # username: server
  DATABASE_USERNAME:
  # password: password
  DATABASE_PASSWORD:
